// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpbgdgwigjweqzanhfui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYmdkZ3dpZ2p3ZXF6YW5oZnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0ODYzMDYsImV4cCI6MjA1MjA2MjMwNn0.XDMyy14QoUP_h4xfgOYAgKBdUZrS2T4U1FjAdoVYK8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);